GET http://localhost:3000/ping

###
GET http://localhost:3000/distributions/uniform HTTP/1.1
Content-Type: application/json

{
    "lowerBound": 1,
    "upperBound": 4,
    "numberOfSamples": 50
}

###
GET http://localhost:3000/distributions/normal HTTP/1.1
Content-Type: application/json

{
    "sigma": "1",
    "mu": "0",
    "numberOfSamples": "100000"
}

###
GET http://localhost:3000/distributions/exponential HTTP/1.1
Content-Type: application/json

{
    "lambda": "5",
    "numberOfSamples": "100"
}

###
POST http://localhost:3000/montecarlo/simulate HTTP/1.1
Content-Type: application/json

{
    "daysToSimulate": 100
}